name: Keep Supabase Alive

on:
  schedule:
    - cron: "0 0 */3 * *"

  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Supabase Auth
        run: |
          curl -X POST \
            "https://gugcnntetqarewwnzrki.supabase.co/auth/v1/token?grant_type=password" \
            -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{"email":"nonexistent@reliablestore.in","password":"dummy123"}'
