name: Keep Supabase Alive

on:
  schedule:
    - cron: "0 0 */3 * *"

  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Supabase
        run: |
          curl -I https://gugcnntetqarewwnzrki.supabase.co/rest/v1/
